### ISSUE TITLE
Auto record with Workshop Maps

### ISSUE THREAD

**Issue by Versatile-BFG** [GameTech/WarMod#2]
Auto record doesn't work with workshop maps. I believe it has to do with this line from warmod.sp:

line 521:   GetCurrentMap(g_map, sizeof(g_map));

Adding something like this below it should fix the issue:

line 522:   ReplaceString(g_map, sizeof(g_map), "\", "-");

**Comment by mavrick** [comment]
This explains a lot, especially with running tournaments and no demos. There is the option to force GOTV manually in the warmod config files however.

**Comment by Versatile-BFG** [comment]
Could be different code as this is the CS:S code but one would think it is very similar to this.
